apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-dep
  strategy: {}
  template:
    metadata:
      labels:
        app: my-dep
    spec:
      volumes:
        - name:  data
          emptyDir: {}
        - name: redis-config
          configMap:
            name: redis-config
      containers:
      - image: redis:alpine
        name: redis
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: data
            mountPath:  /redis-masters-data
          - name: redis-config
            mountPath: /redis-master
        resources: 
            requests: 
              cpu: "0.2"
status: {}
